- name: configuring user server
  hosts: user
  become: yes
  tasks:
  - name: enable the nodejs
    command: dnf module enable nodejs:20 -y
  - name: Installing the nodejs
    package:
      name: nodejs
      state: present
  - name: create roboshop user
    user:
      name: roboshop
      system: true
      home: /app
      shell: /sbin/nologin
      comment: "roboshop system user"
  - name: remove the app directory
    file:
      path: /app
      state: absent
  - name: delete user.zip in /tmp
    file:
      path: /tmp/user.zip
      state: absent
  - name: create app directory
    file: 
      path: /app
      state: directory
  - name: download user code
    get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
      dest: /tmp/user.zip
  - name: unxip the user code
    unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes
  - name: Install dependencies
    community.general.npm:
      path: /app
  - name: copying the user.service
    copy:
      src: user.service.j2
      dest: /etc/systemd/system/user.service
  - name: daemon reload
    systemd_service:
      name: catalogue
      daemon_reload: true
  - name: enable and start user
    service:
      name: restarted
      enabled: yes

