- name: configuring shipping server
  hosts: shipping
  become: yes
  tasks:
  - name: Installing maven 
    package:
      name: maven
      state: present
  - name: creating roboshop user
    user:
      name: roboshop
      system: true
      home: /app
      shell: /sbin/nologin 
      comment: "roboshop system user"
  - name: remove the app directory
    file:
      path: /app
      state: absent
  - name: delete shipping.zip in /tmp
    file:
      path: /tmp/shipping.zip
      state: absent
  - name: create app directory
    file: 
      path: /app
      state: directory
  - name: download shipping code
    get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
      dest: /tmp/cart.zip
  - name: unzip the shipping code
    unarchive:
      src: /tmp/shipping.zip
      dest: /app
      remote_src: yes
  - name: install dependencies
    command: mvn clean package 
    args:
      chdir: /app
  - name: move shipping.jar
    command: mv target/shipping-1.0.jar shipping.jar 
    args:
      chdir: /app
  - name: copying shipping service
    copy:
      src: shipping.service.j2
      dest: /etc/systemd/system/shipping.service
  - name: Installing mysql
    package:
      name: mysql
      state: present
  - name: load mysql data
    community.mysql.mysql_db:
      state: import
      name: all
      login_host: "{{ MYSQL_HOST }}"
      login_user: root
      login_password: RoboShop@1
      target: "{{ item }}"
    loop:
    - /app/db/schema.sql
    - /app/db/app-user.sql
    - /app/db/master-data.sql
  - name: deamon reload
    systemd_service:
      name: shipping
      daemon_reload: true
  - name: enable and start shipping
    service:
      name: shipping
      state: restarted
      enabled: yes