- name: for my practice
  hosts: local
  connection: local
  vars:
    noor: ninja
  tasks:
  - name: loops
    debug:
      msg: "{{ item }}"
    loop: 
    - noor 
    - afrin 
    - shanu
    - milsaht
    when: noor == "{{ noor }}"